### ISSUE TITLE
Don't prevent .vscode/settings.json from being committed

### ISSUE THREAD

**Issue by stevebaxter** [datreeio/datree-pr-checks#32]
It's incorrect to prevent .vscode/settings.json from being committed. This is a completely reasonable thing to do if you want to share settings as a team, e.g. tabs, spelling etc.

See:

https://github.com/datreeio/datree-pr-checks/blob/master/patterns.md#unwanted-files

**Comment by shimont** [comment]
Thank you for opening the ticket, we will check the issue and get back to you

**Comment by eyarz** [comment]
We removed the pattern (.vscode/settings.json) from your account.
